### ISSUE TITLE
Helm chart: Hue monitoring doesn't work as expected (only from "default" namespace)

### ISSUE THREAD

**Issue by swabb** [gethue/hue#34]
Describe the bug:

When Hue is deployed to the personal namespace, monitoring doesn't work because the namespace selector is hardcoded to 'default'.

https://github.com/gethue/hue/blob/master/tools/kubernetes/helm/hue/templates/servicemonitor-hue.yaml#L15
```yaml
  namespaceSelector:
    matchNames:
    - default
```
Hue chart version deployed to Kubernetes:
```yaml
  source:
    repoURL: "https://helm.gethue.com"
    chart: "hue"
    targetRevision: "1.0.3"
```
 Hue™ 4.10.0
